server:
  port: 9527

spring:
  application:
    name: cloud-gatewat-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           #路由id，没有固定规则但是要求唯一，建议配合服务名
         # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cgq-cloud-payment-service
          predicates:
            - Path=/getPaymentById/** #断言，路径相匹配的进行路由
        - id: payment_rouch2
          #uri: http://localhost:8001
          uri: lb://cgq-cloud-payment-service
          #after表示要在这个时间到达之后匹配对应的路由
          predicates:
            - Path=/getServerPort/**
            - After=2020-11-03T16:59:13.827+08:00[Asia/Shanghai]
            #- Before=2020-11-03T16:59:13.827+08:00[Asia/Shanghai]
            #- Between=2020-11-03T16:59:13.827+08:00[Asia/Shanghai]
            #- Cookie=username,ADMINISTRATOR
            #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
   service-url:
    register-with-eureka: true
    fetch-register: true
    defaultZone: http://eureka7001.com:7001/eureka
