server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.119.128
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}