server:
  port: 8002

spring:
  application:
    name: cgq-cloud-payment-servcie #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tests?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456789

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有实体类所在包
  type-aliases-package: com.cloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

      ####test